apiVersion: v1
kind: Pod
metadata:
  name: demo-kotlinapp
  labels:
    role: webapp
spec:
  containers:
    - name: web
      image: watrv41/demo-kotlincreatedbywatrv41
      ports:
        - containerPort: 80
          name: web
          protocol: TCP