name: 'Terraform'

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest
    name: 'Terraform'
    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_AD_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_AD_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_AD_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_AD_TENANT_ID }}

    defaults:
      run:
        shell: bash
        working-directory: terraform

    steps:

      - name: 'Checkout'
        uses: actions/checkout@v2

#      - name: 'Install pre-reqs'
#        run: |
#          curl -SL "https://releases.hashicorp.com/terraform/1.2.5/terraform_1.2.5_linux_amd64.zip" --output terraform.zip
#          unzip "terraform.zip"
#          mv terraform /usr/local/bin
#          terraform --version
#          rm terraform.zip
#
#      - name: 'Install TFLint'
#        run: |
#          wget https://github.com/terraform-linters/tflint/releases/download/v0.25.0/tflint_linux_amd64.zip
#          unzip tflint_linux_amd64
#          mv tflint /usr/local/bin

#      - name: Terraform init
#        run: terraform init
#
#      - name: Terraform plan
#        run: terraform plan
#
#      - name: terraform apply
#        run: terraform apply -auto-approve

      - name: 'Terraform Format'
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_action_version: 0.14.8
          tf_action_subcommand: 'fmt'
          tf_actions_working_dir: "./terraform"
      - name: 'Terraform Init'
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_action_version: 0.14.8
          tf_action_subcommand: 'init'
          tf_actions_working_dir: "./terraform"
      - name: 'Terraform Plan'
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_action_version: 0.14.8
          tf_action_subcommand: 'plan'
          tf_actions_working_dir: "./terraform"



