name: Continuous Integration Demo

on:
  push:
    branches: [main, feature/branch]

  workflow_dispatch:
  
jobs:
  build:
    runs-on:  ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Run a one-line script
        run: echo Hello, world!

      - name: running a custom step
        run: |
          ls -al

      - name: Log in with Azure action
        uses: azure/login@v1
        with:
          creds: '${{ secrets.AZURE_CREDENTIALS }}'

      - uses: azure/aks-det-context@v1
        with:
          creds: '${{ secrets.AZURE_CREDENTIALS }}'
          cluster-name: githubactionsaks
          resource-group: DefaultResourceGroup-SE

      - name: RUN AZ Command
        run: |
          az account show
          az group list
      - name: Run a multi-line script
        if: always()
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
      - name: check java version
        run: java -version
      - name: gradle build
        run: gradle build
      - name: gradlew build
        run: ./gradlew build
      - name: docker version
        run: |
          docker -v
          docker images -a
      - name: docker build
        run: |
          docker build . -t watrv41/demo-kotlin2.0
          docker images -a
      - name: docker login
        run: docker login -u ${{ secrets.dockerhubusername}} -p ${{ secrets.dockerhubpassword }}
      - name: docker image push
        run: docker push watrv41/demo-kotlin2.0
